title: "Ruevko's Slides"
description: "slides and stuff Rafael Castro has presented"
author:
  name: "Roger Rafael Castro Zambrano"
  url: https://ruevko.github.io

baseurl: /slides

highlighter: none

exclude:
  - .jekyll-cache
  - Gemfile*    #
  - LICENSE.md  #

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  tags:
    output: true
    permalink: /tag/:name
  posts:
    output: true
    permalink: /:year/:slug-post
  slides:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      slide-ext: ""
      slide-inc: true
